Class {
	#name : 'Caller',
	#superclass : 'CallerType',
	#category : 'StaticCallsFinder',
	#package : 'StaticCallsFinder'
}

{ #category : 'as yet unclassified' }
Caller >> performSend: anObject [

	           self send: anObject 
]

{ #category : 'instructions' }
Caller >> send: x [ 

	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.


	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
		
]
