Class {
	#name : 'Caller',
	#superclass : 'Object',
	#category : 'StaticCallsFinder',
	#package : 'StaticCallsFinder'
}

{ #category : 'instructions' }
Caller >> send: x [ 

	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.


	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
	
	
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.
	x yourself.x yourself.
		
]

{ #category : 'instructions' }
Caller >> sendSStatic: x [ 

	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.


	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
		
]
