Class {
	#name : 'SCaller',
	#superclass : 'CallerType',
	#category : 'StaticCallsFinder',
	#package : 'StaticCallsFinder'
}

{ #category : 'as yet unclassified' }
SCaller >> performSend: anObject [

	           self sendSStatic: anObject 
]

{ #category : 'instructions' }
SCaller >> sendSStatic: x [ 

	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.


	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
	
	
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.
	x _Object_yourself.x _Object_yourself.
		
]
